# Generated by Django 5.1.7 on 2025-03-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_permission_is_public_alter_permission_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='is_public',
            new_name='is_publihed',
        ),
    ]
