# Generated by Django 5.1.7 on 2025-03-31 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_alter_permission_date_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='is_publihed',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='permission',
            name='reason',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permission.interdiction'),
        ),
    ]
