# Generated by Django 5.1.7 on 2025-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_rename_is_publihed_permission_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
