# Generated by Django 5.1.7 on 2025-04-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_alter_permission_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
