# Generated by Django 5.1.7 on 2025-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0007_permission_lat_permission_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='lat',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='lon',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
