# Generated by Django 5.1.7 on 2025-04-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0008_alter_permission_lat_alter_permission_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='date_search',
            new_name='date_register',
        ),
    ]
