# Generated by Django 5.1.7 on 2025-04-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0009_rename_date_search_permission_date_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='is_published',
            new_name='authorized',
        ),
    ]
